// gen-agent-md writes AGENT.md at the module root — an OpenCLI-style
// manifest composed of two parts:
//
//  1. The hand-edited prose from .claude/skills/pipe2-cli/SKILL.md
//     (frontmatter stripped). That's the one source of truth for the
//     agent contract, install steps, quickstart, and workflows.
//
//  2. The auto-generated "Commands" section walked from the live cobra
//     command tree — every subcommand, flag, type, and default.
//
// AGENT.md and SKILL.md therefore share the prose: you edit SKILL.md,
// regen AGENT.md, and the two files never diverge.
//
// Usage (from packages/pipe2-cli/):
//
//	go run ./cmd/gen-agent-md
//
// CI drift check: `git diff --exit-code AGENT.md` after running this.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	pipe2cli "github.com/pipe2-ai/pipe2-cli"
	"github.com/pipe2-ai/pipe2-cli/internal/cli"
)

func main() {
	root, err := moduleRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, "module root:", err)
		os.Exit(1)
	}

	agentMD := generateAgentMD(cli.NewRootCmd("dev"), pipe2cli.SkillMD)
	path := filepath.Join(root, "AGENT.md")
	if err := os.WriteFile(path, []byte(agentMD), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write AGENT.md:", err)
		os.Exit(1)
	}
	fmt.Fprintln(os.Stderr, "wrote", path)
}

// moduleRoot walks up from the current working directory until it finds a
// go.mod containing module github.com/pipe2-ai/pipe2-cli. That's the
// file the public repo root will contain after subtree split, so we
// anchor both output paths to it and avoid hardcoding packages/pipe2-cli/.
func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		goMod := filepath.Join(dir, "go.mod")
		if data, err := os.ReadFile(goMod); err == nil {
			if strings.Contains(string(data), "module github.com/pipe2-ai/pipe2-cli") {
				return dir, nil
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("pipe2-cli go.mod not found in any parent of cwd")
		}
		dir = parent
	}
}

// stripFrontmatter removes a leading YAML `---\n...\n---\n` block if
// present. SKILL.md has one (name, description); AGENT.md doesn't need it.
func stripFrontmatter(md []byte) []byte {
	if !bytes.HasPrefix(md, []byte("---\n")) {
		return md
	}
	end := bytes.Index(md[4:], []byte("\n---\n"))
	if end < 0 {
		return md
	}
	rest := md[4+end+len("\n---\n"):]
	return bytes.TrimLeft(rest, "\n")
}

// generateAgentMD composes AGENT.md: skill prose (frontmatter stripped)
// followed by the auto-generated cobra command tree.
func generateAgentMD(root *cobra.Command, skillMD []byte) string {
	var b strings.Builder
	b.WriteString("<!--\n")
	b.WriteString("  Auto-generated by `go run ./cmd/gen-agent-md`.\n")
	b.WriteString("  Do not edit by hand — the prose comes from\n")
	b.WriteString("  .claude/skills/pipe2-cli/SKILL.md and the command\n")
	b.WriteString("  reference below is walked from the live cobra tree.\n")
	b.WriteString("  CI regenerates on every PR and fails on drift.\n")
	b.WriteString("-->\n\n")

	// 1. Skill prose (frontmatter stripped).
	b.Write(stripFrontmatter(skillMD))
	if !bytes.HasSuffix(stripFrontmatter(skillMD), []byte("\n")) {
		b.WriteString("\n")
	}
	b.WriteString("\n")

	// 2. Command reference — TOC then per-subcommand sections.
	b.WriteString("---\n\n")
	b.WriteString("## Command reference\n\n")
	for _, sub := range root.Commands() {
		if sub.Hidden || sub.Name() == "help" || sub.Name() == "completion" {
			continue
		}
		anchor := strings.ToLower(strings.ReplaceAll(sub.Name(), " ", "-"))
		fmt.Fprintf(&b, "- [`pipe2 %s`](#pipe2-%s) — %s\n", sub.Name(), anchor, sub.Short)
	}
	b.WriteString("\n")

	for _, sub := range root.Commands() {
		if sub.Hidden || sub.Name() == "help" || sub.Name() == "completion" {
			continue
		}
		writeCommandSection(&b, sub, []string{"pipe2"})
	}

	// Footer intentionally has no date — embedding one (even at day
	// granularity) makes the CI drift check fire every time the calendar
	// flips between local regen and CI run. `git log -- AGENT.md` already
	// records when the file was regenerated, so the stamp is redundant.
	b.WriteString("\n---\n\n")
	b.WriteString("_Command reference auto-generated from the live cobra command tree — do not hand-edit._\n")
	return b.String()
}

func writeCommandSection(b *strings.Builder, c *cobra.Command, parents []string) {
	full := append(parents, c.Name())
	fullPath := strings.Join(full, " ")
	anchor := strings.ReplaceAll(fullPath, " ", "-")
	fmt.Fprintf(b, "### `%s`\n\n", fullPath)
	fmt.Fprintf(b, "<!-- anchor: %s -->\n\n", anchor)
	if c.Short != "" {
		fmt.Fprintf(b, "%s\n\n", c.Short)
	}
	if c.Long != "" && c.Long != c.Short {
		fmt.Fprintf(b, "%s\n\n", c.Long)
	}
	if use := c.UseLine(); use != "" {
		fmt.Fprintf(b, "```\n%s %s\n```\n\n", strings.Join(parents, " "), use)
	}

	// Local flags only — global flags are covered once at the top.
	locals := []string{}
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		line := fmt.Sprintf("- `--%s`", f.Name)
		if f.Shorthand != "" {
			line += fmt.Sprintf(" / `-%s`", f.Shorthand)
		}
		line += fmt.Sprintf(" (`%s`)", f.Value.Type())
		if f.DefValue != "" && f.DefValue != "false" {
			line += fmt.Sprintf(" default `%s`", f.DefValue)
		}
		if f.Usage != "" {
			line += " — " + f.Usage
		}
		locals = append(locals, line)
	})
	if len(locals) > 0 {
		b.WriteString("**Flags:**\n\n")
		for _, l := range locals {
			b.WriteString(l)
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	for _, sub := range c.Commands() {
		if sub.Hidden || sub.Name() == "help" {
			continue
		}
		writeCommandSection(b, sub, full)
	}
}
