// gen-docs walks the pipe2 command tree and writes one Starlight-compatible
// Markdown file per command under the target directory. It is the source of
// truth for every page under docs/cli/reference/ — hand-editing those files
// is pointless because CI re-runs this tool and diffs the result.
//
//	go run ./cmd/gen-docs --out ../../docs/src/content/docs/cli/reference
//
// Exit codes:
//
//	0  success
//	1  write failure
//	2  usage error
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/pipe2-ai/pipe2-cli/internal/cli"
)

func main() {
	out := flag.String("out", "../docs/src/content/docs/cli/reference", "output directory")
	flag.Parse()

	if err := os.MkdirAll(*out, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "mkdir:", err)
		os.Exit(1)
	}

	// Wipe stale pages so a removed command actually disappears from the
	// docs site instead of lingering as an orphan.
	if err := cleanDir(*out); err != nil {
		fmt.Fprintln(os.Stderr, "clean:", err)
		os.Exit(1)
	}

	root := cli.NewRootCmd("dev")

	// Disable cobra's built-in "Auto generated by spf13/cobra on
	// dd-MMM-YYYY" footer on every command in the tree. It's per-day
	// granularity so the CI docs drift check fires every time the
	// calendar flips between local regen and the CI run, even when
	// no command surface actually changed. Git log already records
	// when the pages were regenerated, so the stamp is redundant.
	// Cobra's DisableAutoGenTag is not inherited — it has to be set
	// on every command individually, so walk the tree.
	disableAutoGenTag(root)

	// Cobra emits files as "pipe2_auth_login.md". Parse the path with
	// underscore splitting to recover the canonical command path, then
	// build Starlight frontmatter from that. We DO NOT do a global
	// underscore replace on the body — that mangles env var names like
	// XDG_CONFIG_HOME.
	filePrepender := func(path string) string {
		parts := commandPathFromFile(path) // ["pipe2","auth","login"]
		title := strings.Join(parts, " ")  // "pipe2 auth login"
		short := findShortFromParts(root, parts)
		return fmt.Sprintf("---\ntitle: %q\ndescription: %q\nsidebar:\n  order: %d\n---\n\n",
			title, short, orderForParts(parts),
		)
	}

	linkHandler := func(name string) string {
		// Cobra default links are ./pipe2_foo_bar.md — rewrite to the
		// slug format Starlight uses for internal refs.
		slug := strings.TrimSuffix(name, ".md")
		slug = strings.ReplaceAll(slug, "_", "-")
		// The Starlight site is served under /docs so internal links need
		// to include that prefix. Relative links would break the generated
		// `see also` list in each reference page (navigation goes across
		// sibling pages rooted at /docs/cli/reference/).
		return "/docs/cli/reference/" + slug + "/"
	}

	if err := doc.GenMarkdownTreeCustom(root, *out, filePrepender, linkHandler); err != nil {
		fmt.Fprintln(os.Stderr, "generate:", err)
		os.Exit(1)
	}

	// Rename files (not content) so URLs use hyphens.
	if err := renameFilesUnderscoresToHyphens(*out); err != nil {
		fmt.Fprintln(os.Stderr, "rename:", err)
		os.Exit(1)
	}

	fmt.Fprintln(os.Stderr, "wrote CLI reference to", *out)
}

// cleanDir removes all .md files under dir but leaves the directory itself
// and any non-markdown siblings (e.g. a README or an index.mdx we hand-wrote
// at the parent level). Keeps a trailing newline in the error path clean.
func cleanDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		if err := os.Remove(filepath.Join(dir, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

// commandPathFromFile turns a cobra-generated file path like
// ".../pipe2_auth_login.md" into ["pipe2","auth","login"]. This is the
// canonical command path we use for both the title and findShortFromParts.
func commandPathFromFile(path string) []string {
	name := strings.TrimSuffix(filepath.Base(path), ".md")
	return strings.Split(name, "_")
}

// renameFilesUnderscoresToHyphens renames files but leaves body content
// untouched. Cobra's default filename is "pipe2_auth_login.md"; Starlight
// URLs look nicer with hyphens, and we already rewrote intra-doc links
// via the linkHandler.
func renameFilesUnderscoresToHyphens(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		old := filepath.Join(dir, e.Name())
		newName := strings.ReplaceAll(e.Name(), "_", "-")
		if newName == e.Name() {
			continue
		}
		if err := os.Rename(old, filepath.Join(dir, newName)); err != nil {
			return err
		}
	}
	return nil
}

// orderForParts assigns a stable sidebar ordering from the second segment
// of the command path ("pipe2 auth login" -> "auth"). Root sorts first,
// unknown top-levels sort last (order 99).
func orderForParts(parts []string) int {
	if len(parts) < 2 {
		return 0 // "pipe2" root page
	}
	switch parts[1] {
	case "auth":
		return 10
	case "pipelines":
		return 20
	case "runs":
		return 30
	case "assets":
		return 40
	case "credits":
		return 50
	case "schema":
		return 60
	case "skill":
		return 70
	default:
		return 99
	}
}

// disableAutoGenTag sets cmd.DisableAutoGenTag = true on every command
// in the tree. Cobra doesn't inherit the flag from parent to child, so
// a simple `root.DisableAutoGenTag = true` only suppresses the footer
// on the root command's page.
func disableAutoGenTag(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, c := range cmd.Commands() {
		disableAutoGenTag(c)
	}
}

// findShortFromParts walks the cobra tree to find the command whose path
// matches ["pipe2","auth","login"] and returns its Short description. A
// miss returns "" so frontmatter stays valid.
func findShortFromParts(root *cobra.Command, parts []string) string {
	if len(parts) == 0 || parts[0] != "pipe2" {
		return ""
	}
	cur := root
	for _, p := range parts[1:] {
		var next *cobra.Command
		for _, c := range cur.Commands() {
			if c.Name() == p {
				next = c
				break
			}
		}
		if next == nil {
			return ""
		}
		cur = next
	}
	return cur.Short
}
